config/routes.rb
Rails.application.routes.draw do
  # ルートパス(未ログイン時トップ画面)
  root to: "users/homes#top"

  # gem devise 管理者
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
  }

  # gem devise 利用者
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }
  # ゲストユーザーログイン
  post '/homes/guest_sign_in', to: 'users/homes#new_guest'

  # 使い方ページの表示
  get '/how_to' => 'users/homes#how_to'

  # 利用者退会画面の表示
  get '/mypages/unsubscribe' => 'users/mypages#unsubscribe'

  # 利用者の退会処理(有効フラグカラムを退会済に変える)
  patch '/mypages/withdraw' => 'users/mypages#withdraw'

  # タスクを開始したときの処理(タスクテーブルにデータが作成される)
  patch '/lists/start' => 'users/lists#start'

  # メモを全て削除する処理
  delete '/memo/destroy_all/:id' => 'users/memos#destroy_all', as: 'destroy_all'

  # ルームを検索する処理
  get '/searchs/room' => 'users/rooms#search', as: 'search_room'

  # URLにadminsを含ませる
  namespace :admins do
    resources :contacts, only: [:index, :show, :update]
    resources :rooms, only: [:index, :update]
    resources :users, only: [:index, :update]
    resources :analysis, only: [:index]
  end

  # URLにusersを含ませない
  scope module: :users do
    resources :rooms, except: [:index, :edit, :destroy]
    resources :contacts, only: [:new, :create]
    resources :mains, only: [:show, :update]
    resources :lists, only: [:create, :update, :destroy]
    resources :memos, only: [:create, :destroy]
    resources :analysis, only: [:show, :edit]
    # URLにidをもたせないため単数形
    resource :mypages, only: [:edit, :update]
  end
end

app/controllers/admins/analysis_controller.rb
class Admins::AnalysisController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.group_by_day(:created_at).count
    @rooms = Room.group_by_day(:created_at).count
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @user_all = User.all
    @users = User.page(params[:page]).per(10)
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_is_deleted_params)
    redirect_to request.referer
  end

  private

  def user_is_deleted_params
    params.permit(:is_deleted)
  end
end

app/controllers/users/analysis_controller.rb
class Users::AnalysisController < ApplicationController
  before_action :authenticate_user!

  def show
    set_analysis
    @all_tasks_graph = {
      "未着手" => @off_tasks.count,
      "実行中" => @on_tasks.count,
      "終了済" => @finished_tasks.count,
    }
    # アクセス制限
    unless current_user.present_room == Room.find(params[:id]).id
      flash[:alert_analysis] = "他のルームの分析画面は閲覧できません。"
      redirect_to analysis_path(current_user.present_room)
    end
  end

  def edit
    set_analysis
    @room_user           = RoomUser.find(params[:id])
    @on_tasks_user       = @on_tasks.where(user_id: @room_user.user_id)
    @finished_tasks_user = @finished_tasks.where(user_id: @room_user.user_id)
    # アクセス制限
    unless RoomUser.where(room_id: current_user.present_room).pluck(:id).include?(@room_user.id)
      flash[:alert_analysis] = "他のルームの分析画面は閲覧できません。"
      redirect_to analysis_path(current_user.present_room)
    end
  end

  private

  def set_analysis
    @room           = Room.find(current_user.present_room)
    @room_users     = RoomUser.includes([:user]).where(room_id: current_user.present_room)
    @all_tasks      = Task.where(room_id: current_user.present_room)
    @off_tasks      = Task.where(room_id: current_user.present_room,
                                 status: 0)
    @on_tasks       = Task.includes([:user]).where(room_id: current_user.present_room,
                                                   status: 1).order(updated_at: :asc)
    @finished_tasks = Task.includes([:user]).where(room_id: current_user.present_room,
                                                   status: 2).order(updated_at: :desc)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  before_action :authenticate_user!
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/contacts_controller.rb
class Users::ContactsController < ApplicationController
  before_action :authenticate_user!
  def new
    @contacts = Contact.where(user_id: current_user.id).reverse_order
    @contact  = Contact.new
  end

  def create
    @contacts = Contact.where(user_id: current_user.id)
    @contact  = Contact.new(contact_params)
    @contact.user_id = current_user.id
    if @contact.save
      flash[:notice_contact] = "お問い合わせが送信されました。"
      redirect_to new_contact_path
    else
      flash.now[:alert_contact] = "タイトル・お問い合わせ内容を確認してください。"
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:title, :body)
  end
end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
  def top
  end

  def how_to
  end

  # ゲストログイン用
  def new_guest
    user          = User.new(user_params)
    user.name     = "ゲストユーザー"
    user.email    = SecureRandom.alphanumeric(15) + "@email.com"
    user.password = SecureRandom.alphanumeric(10)
    user.save
    sign_in user
    redirect_to how_to_path
  end

  private

  def user_params
    params.permit(:name, :email, :password)
  end
end

app/controllers/users/lists_controller.rb
class Users::ListsController < ApplicationController
  before_action :authenticate_user!

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    # ログイン中の利用者のpresent_room値をTODOリストのroom_idに代入
    @task.room_id = current_user.present_room
    @task.status = 0
    @task.save
    after_set_lists
  end

  def destroy
    set_lists
    @task.destroy
    after_set_lists
  end

  def start
    set_lists
    @task.user_id = current_user.id
    @task.status = 1
    @task.update(task_status_params)
    after_set_lists
  end

  def update
    set_lists
    @task.status = 2
    @task.update(task_status_params)
    after_set_lists
  end

  private

  def set_lists
    @task = Task.find(params[:id])
  end

  def after_set_lists
    @all_tasks      = Task.where(room_id: current_user.present_room)
    @off_tasks      = Task.where(room_id: current_user.present_room,
                                 status: 0)
    @on_tasks       = Task.where(room_id: current_user.present_room,
                                 status: 1)
    @finished_tasks = Task.where(room_id: current_user.present_room,
                                 status: 2).order(updated_at: :desc)
    @all_tasks_graph = {
      "未着手" => @off_tasks.count,
      "実行中" => @on_tasks.count,
      "終了済" => @finished_tasks.count,
    }
  end

  def task_params
    params.require(:task).permit(:body, :importance)
  end

  def task_status_params
    params.permit(:status)
  end

end

app/controllers/users/mains_controller.rb
class Users::MainsController < ApplicationController
  before_action :authenticate_user!
  def show
    set_mains
    @task      = Task.new
    @off_tasks = Task.where(room_id: params[:id],
                            status: 0)
    @memo      = Memo.new
    @memos     = Memo.includes([:user]).where(room_id: params[:id])
    # アクセス制限
    unless current_user.present_room == @room.id
      flash[:alert_enter_room] = "他のルームに参加するためにはパスワードが必要です。"
      redirect_to main_path(current_user.present_room)
    end
  end

  def update
    set_mains
    if @room.update(room_params)
      flash[:notice_enter_room] = "ルームの設定を変更しました。"
      redirect_to main_path(@room.id)
    else
      flash[:alert_analysis] = "設定を正しく入力してください。"
      redirect_to analysis_path(current_user.present_room)
    end
  end

  private

  def set_mains
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name, :goal)
  end
end

app/controllers/users/memos_controller.rb
class Users::MemosController < ApplicationController
  before_action :authenticate_user!
  def create
    @memo         = Memo.new(memo_params)
    @memo.user_id = current_user.id
    @memo.room_id = current_user.present_room
    @memo.save
    set_memos
  end

  def destroy
    # ルームのメモを個別に削除する
    @memo = Memo.find(params[:id])
    @memo.destroy
    set_memos
  end

  def destroy_all
    set_memos
    @memos.destroy_all
  end

  private

  def set_memos
    @memos = Memo.includes([:user]).where(room_id: current_user.present_room)
  end

  def memo_params
    params.require(:memo).permit(:body)
  end
end

app/controllers/users/mypages_controller.rb
class Users::MypagesController < ApplicationController
  before_action :authenticate_user!
  def edit
    set_mypages
    @exist_user_rooms = RoomUser.includes([:room]).where(user_id: current_user.id).select { |n| n.room.is_deleted == "有効" }
  end

  def update
    set_mypages
    if @user.update(user_params)
      flash[:notice_mypage] = "ユーザー情報が変更されました。"
      redirect_to edit_mypages_path(current_user.id)
    else
      @exist_user_rooms = RoomUser.includes([:room]).where(user_id: current_user.id).select { |n| n.room.is_deleted == "有効" }
      flash.now[:alert_mypage] = "ニックネーム・メールアドレスを確認してください。(すでに使用されているメールアドレスは別アカウントに登録できません)"
      render :edit
    end
  end

  def unsubscribe
  end

  # 退会処理(利用者の有効フラグが退会済になる。ログアウト状態にし、ホーム画面に戻る。)
  def withdraw
    set_mypages
    @user.is_deleted = true
    @user.update(user_is_deleted)
    reset_session
    redirect_to root_path
  end

  private

  def set_mypages
    @user = User.find(current_user.id)
  end

  # 利用者のニックネーム/メール/アイコンの変更
  def user_params
    params.require(:user).permit(:name, :email, :image)
  end

  # 利用者の有効フラグを「退会済」にする
  def user_is_deleted
    params.permit(:is_deleted)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_action :authenticate_user!
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :authenticate_user!
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_user!
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # 新規登録後は使い方ページへ遷移
  def after_sign_up_path_for(resource)
    how_to_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/rooms_controller.rb
class Users::RoomsController < ApplicationController
  before_action :authenticate_user!

  def search
    if params[:search_room].blank?
      flash[:alert_search] = "ルームIDを入力してください。"
      redirect_to new_room_path
    else
      # 検索されたルームidのキーを保持してshowアクションへ
      redirect_to room_path(id: params[:search_room].to_i)
    end
  end

  def show
    @room = Room.find(params[:id])
    @user = User.find(current_user.id)
    # アクセス制限
    if @room.is_deleted == "無効"
      flash[:alert_search] = "検索したIDのルームは無効となっています。"
      redirect_to new_room_path
    end
  end

  def update
    @room = Room.find(params[:id])
    # 入力されたものとルームのパスワードが合致すればルームに入れる
    if @room.roompass == params[:roomkey]
      user              = User.find(current_user.id)
      user.present_room = @room.id
      user.save
      # RoomUserテーブルに保存するための処理
      room_user         = RoomUser.new
      room_user.user_id = user.id
      room_user.room_id = @room.id
      # 過去に一度でもルームに入ったことがあれば、RoomUserテーブルに保存されない(重複データを阻止)
      unless RoomUser.find_by(user_id: room_user.user_id, room_id: room_user.room_id)
        room_user.save
      end
      flash[:notice_enter_room] = "ルームに入室しました。"
      redirect_to main_path(@room.id)
    else
      flash.now[:alert_enter_room] = "パスワードが違います。"
      render :show
    end
  end

  def new
    @rooms = Room.all
    @room  = Room.new
  end

  def create
    @room  = Room.new(room_params)
    # ルームのuser_idは現在ログインしている利用者ID(作成した人のデータ)
    @room.user_id = current_user.id
    if @room.save
      # 利用者のpresent_roomカラムを作成したルームIDの値にする
      user              = User.find(current_user.id)
      user.present_room = @room.id
      user.save
      # RoomUserテーブルに保存するための処理
      room_user         = RoomUser.new
      room_user.user_id = user.id
      room_user.room_id = @room.id
      room_user.save
      # 作成したルームに遷移する
      flash[:notice_enter_room] = "ルームを新しく作成しました。"
      redirect_to main_path(@room.id)
    else
      @rooms = Room.all
      flash.now[:alert_new_room] = "ルーム名・パスワードを正しく設定してください。"
      render :new
    end
  end

  private

  # ルームを新規作成する際のメソッド
  def room_params
    params.require(:room).permit(:name, :goal, :roompass, :roompass_confirmation)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :authenticate_user!
  before_action :reject_user, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # ログイン後マイページに遷移する処理
  def after_sign_in_path_for(resource)
    edit_mypages_path(current_user)
  end

  # 退会した利用者がログインできないようにする処理
  def reject_user
    if user = User.find_by(email: params[:user][:email].downcase)
      if user.valid_password?(params[:user][:password]) && (!user.active_for_authentication?)
        flash[:notice] = "このアカウントは利用できません。"
        redirect_to new_user_session_path
      end
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  before_action :authenticate_user!
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/analysis_helper.rb
module Admins::AnalysisHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users/analysis_helper.rb
module Users::AnalysisHelper
end

app/views/users/analysis/_all_task.html.erb
<div class="field">
  <%= pie_chart all_tasks_graph %>
</div>
<div class="field mt-3 text-center mx-auto">
  <table class="table table-light">
    <thead class="thead-dark">
      <tr>
        <th>未着手のタスク</th>
        <th>実行中のタスク</th>
        <th>終了済のタスク</th>
        <th>すべてのタスク</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= off_tasks.count %></td>
        <td><%= on_tasks.count %></td>
        <td><%= finished_tasks.count %></td>
        <td><%= all_tasks.count %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/users/analysis/_finished_task.html.erb
<table class="table table-sm table-light table-hover">
  <thead class="thead-dark">
    <tr>
      <th>内容</th>
      <th class="small-table">重要度</th>
      <th>タスク担当者</th>
      <th>タスク終了日時</th>
    </tr>
  </thead>
  <tbody>
    <% finished_tasks.each do |finished_task| %>
    <tr>
      <td><%= finished_task.body %></td>
      <td class="<%=status_color(finished_task.importance)%>"><%= finished_task.importance %></td>
      <td><%= simple_body(finished_task.user.name) %></td>
      <td><%= simple_date(finished_task.updated_at) %> &emsp;<%= simple_time(finished_task.updated_at) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/analysis/_task.html.erb
<table class="table table-sm table-light table-hover">
  <thead class="thead-dark">
    <tr>
      <th>内容</th>
      <th class="small-table">重要度</th>
      <th>タスク担当者</th>
      <th>タスク開始日時</th>
      <th class="small-table"></th>
      <th class="small-table"></th>
    </tr>
  </thead>
  <tbody>
    <% on_tasks.each do |task| %>
    <tr>
      <td><%= task.body %></td>
      <td class="<%=status_color(task.importance)%>"><%= task.importance %></td>
      <td><%= simple_body(task.user.name) %></td>
      <td><%= simple_date(task.updated_at) %> &emsp;<%= simple_time(task.updated_at) %></td>
      <td><%= link_to "タスク完了", list_path(task.id), method: :patch, remote:true, class:"btn btn-sm btn-primary" %></td>
      <td><%= link_to "削除", list_path(task.id), method: :delete, remote:true %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/analysis/edit.html.erb
<div class = "row mt-3">
  <div class=" col-6 offset-3">
    <div class="field">
      <h2><%= attachment_image_tag @room_user.user, :image, size: "40x40", format: 'jpg', fallback: "no_image.jpg", class: "" %>
        <span class="text-light font-weight-bold"><%= @room_user.user.name %></span>
        <span class="h4 font-weight-bold">さんの分析</span>
      </h2>
    </div>
  </div>
</div>

<div class="row mt-3">
  <div class="col-2 offset-1 mt-5">
    <div class="field mb-2">
      <span class="text-light font-weight-bold h5">ルーム</span>
    </div>
    <div class="field mb-2"><%= link_to "#{simple_body(@room.name)}", analysis_path(current_user.present_room),class:"text-dark font-weight-bold h6" %></div>
    <div class="field mb-2">
      <span class="text-light font-weight-bold h5">メンバー</span>
    </div>
    <% @room_users.each do |room_user| %>
      <div class="field mb-2">
        <%= attachment_image_tag room_user.user, :image, size: "20x20", format: 'jpg', fallback: "no_image.jpg", class: "" %>
        <%= link_to "#{simple_body(room_user.user.name)}", edit_analysis_path(room_user), class:"text-dark h6" %>
      </div>
    <% end %>
  </div>

  <div class ="col-8">
    <ul class="nav nav-tabs nav-justified mt-5">
      <li class="nav-item">
        <a href="#photo1" class="nav-link active text-dark font-weight-bold" data-toggle="tab">実行中のタスク</a>
      </li>

      <li class="nav-item">
        <a href="#photo2" class="nav-link text-dark font-weight-bold" data-toggle="tab">終了済のタスク</a>
      </li>
    </ul>

    <div class="tab-content mt-3">
      <div id="photo1" class="tab-pane active">
        <div class="field mt-3 text-center mx-auto">
          <table class="table table-sm table-light table-hover">
            <thead class="thead-dark">
              <tr>
                <th>内容</th>
                <th class="small-table">重要度</th>
                <th>タスク担当者</th>
                <th>タスク開始日時</th>
              </tr>
            </thead>
            <tbody>
              <% @on_tasks_user.each do |task| %>
              <tr>
                <td><%= task.body %></td>
                <td class="<%=status_color(task.importance)%>"><%= task.importance %></td>
                <td><%= simple_body(task.user.name) %></td>
                <td><%= simple_date(task.updated_at) %> &emsp;<%= simple_time(task.updated_at) %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

      <div id="photo2" class="tab-pane">
        <div class="field mt-3 text-center mx-auto">
          <table class="table table-sm table-light table-hover">
            <thead class="thead-dark">
              <tr>
                <th>内容</th>
                <th class="small-table">重要度</th>
                <th>タスク担当者</th>
                <th>タスク終了日時</th>
              </tr>
            </thead>
            <tbody>
              <% @finished_tasks_user.each do |finished_task| %>
              <tr>
                <td><%= finished_task.body %></td>
                <td class="<%=status_color(finished_task.importance)%>"><%= finished_task.importance %></td>
                <td><%= simple_body(finished_task.user.name) %></td>
                <td><%= simple_date(finished_task.updated_at) %> &emsp;<%= simple_time(finished_task.updated_at) %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/users/analysis/show.html.erb
<p class="text-center text-danger"><%= flash[:alert_analysis] %></p>
<div class = "row mt-3">
  <div class=" col-6 offset-3">
    <div class="field"><h1><span class="text-light font-weight-bold"><%= @room.name %></span><span class="h4 font-weight-bold">ルームの分析</span></h1></div>
  </div>
</div>

<div class = "row mt-3">
  <div class="col-2 offset-1 mt-5">
    <div class="field mb-2">
      <span class="text-light font-weight-bold h5">ルーム</span>
    </div>
    <div class="field mb-2"><%= link_to "#{simple_body(@room.name)}", analysis_path(current_user.present_room),class:"text-dark font-weight-bold h6" %></div>
    <div class="field mb-2">
      <span class="text-light font-weight-bold h5">メンバー</span>
    </div>
    <% @room_users.each do |room_user| %>
      <div class="field mb-2">
        <%= attachment_image_tag room_user.user, :image, size: "20x20", format: 'jpg', fallback: "no_image.jpg", class: "" %>
        <%= link_to "#{simple_body(room_user.user.name)}", edit_analysis_path(room_user), class:"text-dark h6" %>
      </div>
    <% end %>
  </div>
  <div class ="col-8">
    <ul class="nav nav-tabs nav-justified mt-5">
      <li class="nav-item">
        <a href="#photo1" class="nav-link active text-dark font-weight-bold" data-toggle="tab">実行中のタスク</a>
      </li>
      <li class="nav-item">
        <a href="#photo2" class="nav-link text-dark font-weight-bold" data-toggle="tab">タスク到達度</a>
      </li>
      <li class="nav-item">
        <a href="#photo3" class="nav-link text-dark font-weight-bold" data-toggle="tab">終了済のタスク</a>
      </li>
      <li class="nav-item">
        <a href="#photo4" class="nav-link text-dark font-weight-bold" data-toggle="tab">ルーム設定変更</a>
      </li>
    </ul>

    <div class="tab-content mt-3">
      <div id="photo1" class="tab-pane active">
        <div class="field mt-3 text-center mx-auto">
          <div id ="ontask_table"><%= render "users/analysis/task", on_tasks: @on_tasks %></div>
        </div>
      </div>
      <div id="photo2" class="tab-pane">
        <div id="all_task_table"><%= render "users/analysis/all_task", all_tasks_graph: @all_tasks_graph, off_tasks: @off_tasks, on_tasks: @on_tasks, finished_tasks: @finished_tasks, all_tasks: @all_tasks %></div>
      </div>
      <div id="photo3" class="tab-pane">
        <div class="field mt-3 text-center mx-auto">
          <div id ="finished_task_table"><%= render "users/analysis/finished_task", finished_tasks: @finished_tasks %></div>
        </div>
      </div>
      <div id="photo4" class="tab-pane">
        <div class="field mt-3 text-center mx-auto">
          <%= form_with model: @room, url: main_path(@room.id), local:true do |f| %>
            <div class="field mt-4">
              <strong>ルーム名(1~20文字)</strong>
            </div>
            <div class="field mt-2">
              <%= f.text_field :name, placeholder:"ルーム名" %>
            </div>
            <div class="field mt-4">
              <strong>ルームの目標</strong>
            </div>
            <div class="field mt-2">
              <%= f.text_field :goal, placeholder:"ルームの目標" %>
            </div>
            <div class="actions mt-4">
              <%= f.submit "変更を保存", class:"btn btn-lg btn-secondary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>