config/routes.rb
Rails.application.routes.draw do
  # ルートパス(未ログイン時トップ画面)
  root to: "users/homes#top"

  # gem devise 管理者
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
  }

  # gem devise 利用者
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }
  # ゲストユーザーログイン
  post '/homes/guest_sign_in', to: 'users/homes#new_guest'

  # 使い方ページの表示
  get '/how_to' => 'users/homes#how_to'

  # 利用者退会画面の表示
  get '/mypages/unsubscribe' => 'users/mypages#unsubscribe'

  # 利用者の退会処理(有効フラグカラムを退会済に変える)
  patch '/mypages/withdraw' => 'users/mypages#withdraw'

  # タスクを開始したときの処理(タスクテーブルにデータが作成される)
  patch '/lists/start' => 'users/lists#start'

  # メモを全て削除する処理
  delete '/memo/destroy_all/:id' => 'users/memos#destroy_all', as: 'destroy_all'

  # ルームを検索する処理
  get '/searchs/room' => 'users/rooms#search', as: 'search_room'

  # URLにadminsを含ませる
  namespace :admins do
    resources :contacts, only: [:index, :show, :update]
    resources :rooms, only: [:index, :update]
    resources :users, only: [:index, :update]
    resources :analysis, only: [:index]
  end

  # URLにusersを含ませない
  scope module: :users do
    resources :rooms, except: [:index, :edit, :destroy]
    resources :contacts, only: [:new, :create]
    resources :mains, only: [:show, :update]
    resources :lists, only: [:create, :update, :destroy]
    resources :memos, only: [:create, :destroy]
    resources :analysis, only: [:show, :edit]
    # URLにidをもたせないため単数形
    resource :mypages, only: [:edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # :registerable,:recoverableは不要なので削除
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  enum is_read: { 未読: false, 既読: true }

  validates :title, presence: true, length: { minimum: 1, maximum: 30 }
  validates :body, presence: true, length: { minimum: 10, maximum: 400 }
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :body, presence: true, length: { minimum: 1 }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :memos
  has_many :tasks
  has_many :room_users
  belongs_to :user

  # gem attr_encrypted の記述、カラムの暗号化復号化に使用
  attr_encrypted :roompass, key: ENV['ROOMPASS']

  enum is_deleted: { 有効: false, 無効: true }

  validates :name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :roompass, presence: true, length: { minimum: 3, maximum: 20 }, confirmation: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :room

  enum importance: { HIGH: 0, MIDDLE: 1, LOW: 2 }
  enum status: { 未着手: 0, 実行中: 1, 終了済: 2 }

  validates :body, presence: true, length: { minimum: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # :recoverableは不要なので削除
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :contacts
  has_many :memos
  has_many :rooms
  has_many :tasks
  has_many :room_users

  # 退会処理用(users::sessions_controllerで使用)
  def active_for_authentication?
    super && (is_deleted == "有効")
  end

  # refileの画像処理で必要
  attachment :image

  enum is_deleted: { 有効: false, 退会済: true }

  validates :name, presence: true, length: { minimum: 1 }
end

app/controllers/admins/contacts_controller.rb
class Admins::ContactsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @contact_all = Contact.all
    @contacts = Contact.page(params[:page]).per(15).reverse_order
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    @contact.is_read = true
    @contact.update(contact_is_read_params)
    redirect_to admins_contact_path(@contact.id)
  end

  private

  def contact_is_read_params
    params.permit(:is_read)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/users/contacts_controller.rb
class Users::ContactsController < ApplicationController
  before_action :authenticate_user!
  def new
    @contacts = Contact.where(user_id: current_user.id).reverse_order
    @contact  = Contact.new
  end

  def create
    @contacts = Contact.where(user_id: current_user.id)
    @contact  = Contact.new(contact_params)
    @contact.user_id = current_user.id
    if @contact.save
      flash[:notice_contact] = "お問い合わせが送信されました。"
      redirect_to new_contact_path
    else
      flash.now[:alert_contact] = "タイトル・お問い合わせ内容を確認してください。"
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:title, :body)
  end
end

app/helpers/admins/analysis_helper.rb
module Admins::AnalysisHelper
end

app/helpers/admins/contacts_helper.rb
module Admins::ContactsHelper
end

app/helpers/admins/logs_helper.rb
module Admins::LogsHelper
end

app/helpers/admins/rooms_helper.rb
module Admins::RoomsHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # 年月日表示
  def simple_date(date)
    date.strftime("%Y/%m/%d")
  end

  # 月日表示
  def super_simple_date(date)
    date.strftime("%m/%d")
  end

  # 時間表示
  def simple_time(time)
    time.strftime("%H:%M:%S")
  end

  # 時間(秒なし)表示
  def super_simple_time(time)
    time.strftime("%H:%M")
  end

  # テキストの内容表示(11文字以上なら「10文字...」と表示する)
  def simple_body(body)
    if body.length >= 11
      body[0..9] + "..."
    else
      body
    end
  end

  # テキストの色が既読/有効/低いなら緑、普通なら黄、未読/無効/退会済/高いなら赤
  def status_color(status)
    if (status == "既読") || (status == "有効") || (status == "LOW")
      "text-success"
    elsif status == "MIDDLE"
      "text-warning"
    else
      "text-danger"
    end
  end
end

app/helpers/users/analysis_helper.rb
module Users::AnalysisHelper
end

app/helpers/users/contacts_helper.rb
module Users::ContactsHelper
end

app/helpers/users/homes_helper.rb
module Users::HomesHelper
end

app/helpers/users/lists_helper.rb
module Users::ListsHelper
end

app/helpers/users/mains_helper.rb
module Users::MainsHelper
end

app/helpers/users/memos_helper.rb
module Users::MemosHelper
end

app/helpers/users/mypages_helper.rb
module Users::MypagesHelper
end

app/helpers/users/rooms_helper.rb
module Users::RoomsHelper
end

app/views/admins/contacts/index.html.erb
<div class="container">

  <div class ="row">
    <div class ="col text-center mx-auto">
      <h1><strong><span class="text-light">お問い合わせ</span>一覧</strong></h1><h5>全<span class="h4 font-weight-bold"> <%= @contact_all.count%></span> 件</h5>
    </div>
  </div>

  <div class="row">
    <div class="col text-center mx-auto">
      <table class="table table-sm table-hover">
        <thead class="thead-dark">
          <tr>
            <th>お問い合わせID</th>
            <th>利用者ID</th>
            <th>利用者名</th>
            <th>タイトル</th>
            <th>送信時間</th>
            <th>ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody class ="table-bordered table-light">
          <% @contacts.each do |contact| %>
          <tr>
            <td><%= contact.id %></td>
            <td><%= contact.user_id %></td>
            <td><%= contact.user.name %></td>
            <td><%= simple_body(contact.title) %></td>
            <td><%= simple_date(contact.created_at) %><br><%= simple_time(contact.created_at) %></td>
            <td class=<%= status_color(contact.is_read) %>><%= contact.is_read %></td>
            <td><%= link_to "詳細確認", admins_contact_path(contact.id), method: :patch, class:"font-weight-bold" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>

<%= paginate @contacts %>

app/views/admins/contacts/show.html.erb
<div class = "container">

  <div class ="row">
    <div class ="col text-center mx-auto">
      <h1><strong><span class="text-light">お問い合わせ</span>詳細</strong></h1>
    </div>
  </div>

  <div class ="row mt-3">
    <div class ="col mx-auto">
      <table class="table table-bordered">
        <tr>
          <td class="bg-dark text-light font-weight-bold contact-content">お問い合わせID</td>
          <td class="bg-light"><%= @contact.id %></td>
        </tr>
        <tr>
          <td class="bg-dark text-light font-weight-bold contact-content">利用者名(ID)</td>
          <td class="bg-light"><%= @contact.user.name %> (<%= @contact.user_id %>)</td>
        </tr>
        <tr>
          <td class="bg-dark text-light font-weight-bold contact-content">送信時間</td>
          <td class="bg-light"><%= simple_date(@contact.created_at) %>&emsp;<%= simple_time(@contact.created_at) %></td>
        </tr>
        <tr>
          <td class="bg-dark text-light font-weight-bold contact-content">タイトル</td>
          <td class="bg-light"><%= @contact.title %></td>
        </tr>
        <tr>
          <td class="bg-dark text-light font-weight-bold contact-content">内容</td>
          <td class="bg-light"><%= @contact.body %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class ="row mt-4">
    <div class ="col text-center mx-auto">
      <%= link_to "一覧画面に戻る", admins_contacts_path, class:"btn btn-light" %>
    </div>
  </div>

</div>